name: wildguard

services:
  postgres:
    image: postgres:latest
    container_name: database
    ports:
      - "5432:5432"
    volumes:
      - ~/apps/wildguard/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=Wildguard